up2u_mall/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

up2u_mall/coupons/urls.py
from django.urls import path
from . import views


app_name = 'coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

up2u_mall/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('', views.orders, name='orders'),
]

up2u_mall/up2u_mall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

up2u_mall/orders/models.py
from django.db import models
from shop.models import Product
# 优惠码
from decimal import Decimal
from django.core.validators import MinValueValidator, \
                                    MaxValueValidator
from coupons.models import Coupon


class Order(models.Model):
    name = models.CharField(max_length=50, verbose_name='姓名')
    phone = models.CharField(max_length=11, verbose_name='手机', blank=True)
    city = models.CharField(max_length=100, verbose_name='城市')
    address = models.CharField(max_length=250, verbose_name='地址')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    email = models.EmailField()

    # payment
    pay_id = models.CharField(max_length=150, blank=True)

    # 优惠码
    coupon = models.ForeignKey(Coupon,
                                related_name='orders',
                                null=True,
                                blank=True,
                                on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0,
                                validators=[MinValueValidator(0),
                                MaxValueValidator(100)])

    class Meta:
        ordering = ('-created',)
        verbose_name = '订单'
        verbose_name_plural = verbose_name

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        # return sum(item.get_cost() for item in self.items.all())
        # 考虑优惠
        total_cost = sum(item.get_cost() for item in self.items.all())
        # DE8UG开头的，直接减
        # SALE开头的，打折
        # WHOS开头的，老板定
        if self.coupon.code.startswith('SALE'):
            return total_cost - total_cost * (self.discount / Decimal('100'))
        elif self.coupon.code.startswith('DE8UG'):
            return total_cost - self.discount
        elif self.coupon.code.startswith('WHOS'):
            return 1
        else:
            return total_cost


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Product,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='价格')
    quantity = models.PositiveIntegerField(default=1, verbose_name='数量')

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

up2u_mall/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'placeholder': '收货人姓名',
             'class': "form-control"
             }
        ),
        )
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'placeholder': '手机号码',
             'class': "form-control"
             }
        ),
        )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'placeholder': '邮箱',
             'class': "form-control"
             }
        ),
        )
    city = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'placeholder': '城市',
             'class': "form-control"
             }
        ),
        )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
            'placeholder': '地址',
             'class': "form-control"
             }
        ),
        )
    class Meta:
        model = Order
        fields = ['name', 'phone', 'email', 'city', 'address']

up2u_mall/orders/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created
from coupons.forms import CouponApplyForm

# Create your views here.
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            # order = form.save()
            # 考虑优惠
            order = form.save(commit=False)
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()

            print(order)
            for item in cart:
                OrderItem.objects.create(order=order,
                                        product=item['product'],
                                        price=item['price'],
                                        quantity=item['quantity'])
            cart.clear()
            # 异步发通知
            order_created(order.id)

            # 去支付
            request.session['order_id'] = order.id
            return redirect(reverse('payment:process'))
    else:
        form = OrderCreateForm()

    
    # 优惠券
    coupon_form = CouponApplyForm()

    return render(request,
            'orders/order/create.html',
            {'cart': cart, 
            'form': form,
            'coupon_form': coupon_form })


def orders(request):
    orders = OrderItem.objects.all()
    return render(request,
                  'orders/order/list.html',
                  {'orders': orders}) 

up2u_mall/orders/templates/orders/order/base_form.html
{% for field in form %}
    <div class="form-group">
            <!-- <label class="form-label">{{ field.label_tag }}</label> -->
            {{ field }}

        {% for error in field.errors %}
            <div class="invalid-feedback">
            {{ error }}
            </div>
        {% endfor %}
    {% if field.help_text %}
            <small class="form-text  text-white-50">
            {{ field.help_text }}
            </small>
    {% endif %}
    </div>
{% endfor %}

up2u_mall/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
  订单结算页
{% endblock %}

{% block mystyle %}
 
{% endblock %}
{% block content %}
<section class="section-content bg padding-y-sm">
    <div class="container">
        <main class="card py-5 ">

        <div class="text-center">
            <h2>订单信息</h2>
            <p class="lead">请填写收货地址，并核对订单</p>
          </div>
    
          <div class="row">
            <div class="col-md-4 order-md-1 mb-4 px-lg-5">
              <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-muted">已选商品</span>
                <span class="badge badge-secondary badge-pill">{{cart|length}}</span>
              </h4>
              <ul class="list-group mb-3">
                  {% for item in cart %}
                <li class="list-group-item d-flex justify-content-between lh-condensed">
                  <div>
                    <h6 class="my-0">{{ item.product.name }}</h6>
                    <small class="text-muted">x {{ item.quantity }} 件</small>
                  </div>
                  <span class="text-muted">${{ item.total_price }}</span>
                </li>
                {% endfor %}

                {% if cart.coupon %}
                  <li class="list-group-item d-flex justify-content-between bg-light">
                      <div class="text-success">
                        <h6 class="my-0">优惠码</h6>
                        <small>{{ cart.coupon.code }}</small>
                      </div>
                      <span class="text-success">-￥{{ cart.get_discount |floatformat:"2" }}</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                      <span>总额</span>
                      <strong>￥{{ cart.get_total_price_after_discount |floatformat:"2" }}</strong>
                    </li>
                {% else %}
                
                <li class="list-group-item d-flex justify-content-between bg-light">
                  <div class="text-success">
                    <h6 class="my-0">优惠码</h6>
                    <small>无</small>
                  </div>
                  <span class="text-success">-￥0</span>
                </li>
                <li class="list-group-item d-flex justify-content-between">
                  <span>总额</span>
                  <strong>￥{{ cart.get_total_price |floatformat:"2" }}</strong>
                </li>

                {% endif %}
              </ul>
              <form class="card p-2" action="{% url 'coupons:apply' %}" method="post">
                  <div class="input-group">
                    <!-- <input type="text" class="form-control" placeholder="优惠码"> -->
                    {{ coupon_form }}
                    {% csrf_token %}
                    <div class="input-group-append">
                      <button type="submit" class="btn btn-secondary">优了个惠</button>
                    </div>
                  </div>
              </form>

            </div>
            <div class="col-md-8 order-md-2 text-center px-lg-5">
              <h4 class="mb-3">收货信息</h4>
              <form action="." method="post" class="order-form">
                  <!-- {{ form.as_p }}
                   -->
                  {% csrf_token %}
                  {% include 'orders/order/base_form.html' %}
                  <p><input type="submit" class="btn btn-primary btn-lg btn-block" value="提交订单"></p>
                </form>
            </div>
          </div>
          
          </main>
        </div>
</section>
{% endblock %}

up2u_mall/orders/templates/orders/order/list.html
{% extends "shop/base.html" %}

{% block title %}
所有订单
{% endblock %}

{% block content %}
  <h1>所有订单</h1>

  <div>
    <ul>
      {% for item in orders %}
        <li>
        {{item}}: {{ item.order.email }} {{ item.order.address }} {{ item.product }}
        </li>
      {% endfor %}
    </ul>

  </div>

{% endblock %}