up2u_mall/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

up2u_mall/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('all/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    # 1/coffee/
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('', views.home, name='home'),

]

up2u_mall/up2u_mall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

up2u_mall/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# 商品，分类，
class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)
    isHome = models.BooleanField(default=False)
    detail = models.CharField(max_length=200, default='类别详情')
    description = models.TextField(blank=True, default='类别详情介绍类别详情介绍类别详情介绍类别详情介绍类别详情介绍')
    image = models.ImageField(upload_to='categories/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '类别'
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                        args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True, default="居家必备，老少通吃，特别好用，携带方便")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    price_old = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    isHome = models.BooleanField(default=False)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        verbose_name = '商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                        args=[self.id, self.slug])


class Slide(models.Model):
    image = models.ImageField(upload_to='slides/%Y/%m/%d',
                              blank=True, verbose_name='轮播图')
    url = models.URLField(verbose_name='地址')

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

up2u_mall/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Slide

from cart.forms import CartAddProductForm
from .recommender import Recommender


# Create your views here.
def home(request):
    categories = Category.objects.all()
    products = Product.objects.filter(isHome=True, available=True)

    # 轮播图
    slides = Slide.objects.all()

    # 商品排名
    r = Recommender()
    rank_products = r.get_best_saled()

    context = {
        'categories': categories,
        'products': products,
        'slides': slides,
        'rank_products': rank_products
    }
    return render(request, 'shop/base.html', context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    cart_product_form = CartAddProductForm()

    # 商品推荐
    r = Recommender()
    re_products = r.suggest_products_for([product], 5)

    context = {
        'cart_product_form': cart_product_form,
        'product': product,
        're_products': re_products
    }
    return render(request,
                  'shop/product/detail.html',
                  context)

up2u_mall/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
<section class="section-content bg padding-y-sm">
    <div class="container">
    <div class="card">
      <div class="card-body">
      <div class="row">
        <div class="col-md-3-24"> <strong>当前位置:</strong> </div> <!-- col.// -->
        <nav class="col-md-18-24"> 
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url "shop:home" %}">主页</a></li>
          
          <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></li>
          <li class="breadcrumb-item active" aria-current="page"> {{ product.name }}</li>         
          
        </ol>  
        </nav> <!-- col.// -->
        
      </div> <!-- row.// -->
    </div> <!-- card-body .// -->
  </div> <!-- card.// -->

  <div class="row">
      <div class="col-xl-10 col-md-9 col-sm-12">

      <main class="card">
        <div class="row no-gutters">
          <aside class="col-sm-6 border-right">
            <article class="gallery-wrap"> 
            <div class="img-big-wrap">
            <div> <a href="{{ product.image.url }}" data-fancybox="">
              <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </a></div>
            </div> <!-- slider-product.// -->
            <div class="img-small-wrap"></div>
            </article> <!-- gallery-wrap .end// -->
          </aside>
          <aside class="col-sm-6">
            <article class="card-body">
                <h3 class="title mb-3">{{ product.name }}</h3>

                <div class="mb-3"> 
                  <var class="price h3 text-warning"> 
                    <span class="currency"> ￥</span><span class="num">{{ product.price }}</span>
                  </var> 
                </div> <!-- price-detail-wrap .// -->
                <dl>
                    <dt>商品描述：</dt>
                    <dd><p>{{ product.description }} </p></dd>
                </dl>
                
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ cart_product_form }}
                    {% csrf_token %}
                    <input type="submit" class="btn  btn-outline-warning" value="添加购物车">
                  </form>
            </article>
          </aside>
        </div> <!-- row.// -->
      </main> <!-- card.// -->
    </div><!-- col // -->

    <aside class="col-xl-2 col-md-3 col-sm-12">
        
        {% if re_products %}
          <div class="card mt-3">
            <div class="card-header">
                你可能也喜欢
            </div>
            <div class="card-body row">
              {% for p in re_products %}
                
                  <div class="col-md-12 col-sm-3">
                    <figure class="item border-bottom mb-3">
                        <a href="#" class="img-wrap"> <img src="{{ p.image.url }}" class="img-md"></a>
                        <figcaption class="info-wrap">
                          <a href="{{ p.get_absolute_url }}" class="title">{{ p.name }}</a>
                          <div class="price-wrap mb-3">
                              <span class="price-new">￥{{ p.price }}</span>
                              {% if p.price_old %}
                                <del class="price-old">￥{{ p.price }}
                              {% endif %}
                            </del>
                          </div> <!-- price-wrap.// -->
                        </figcaption>
                    </figure> <!-- card-product // -->
                  </div> <!-- col.// -->
              {% endfor %}
            </div> <!-- card-body.// -->
          </div> <!-- card.// -->
        {% endif %}
      </aside> <!-- col // -->
  

      </div><!-- row.// -->
</div>
</section>

{% endblock %}

up2u_mall/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
 | {% if category %}{{ category.name }}{% else %}商品列表{% endif %}
{% endblock %}

{% block content %}
<section class="section-content bg padding-y-sm">
    <div class="container">
    <div class="card">
      <div class="card-body">
      <div class="row">
        <div class="col-md-3-24"> <strong>当前位置:</strong> </div> <!-- col.// -->
        <nav class="col-md-18-24"> 
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url "shop:home" %}">主页</a></li>
          
          <li class="breadcrumb-item active"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
          
        </ol>  
        </nav> <!-- col.// -->
        
      </div> <!-- row.// -->
    </div> <!-- card-body .// -->
  </div> <!-- card.// -->

  <div class="padding-y-sm">
      <span>共有{{ products|length }}件商品</span>	
      </div>

<div class="row-sm">
    {% for product in products %}
    <div class="col-md-3 col-sm-6">
      <figure class="card card-product">
        <div class="img-wrap"> 
            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        </div>
        <figcaption class="info-wrap">
          <a href="{{ product.get_absolute_url }}" class="title">{{ product.name }}</a>
          <div class="price-wrap">
              <span class="price-new">￥{{ product.price }}</span>
              {% if product.price_old %}
                <del class="price-old">￥{{ product.price }}
              {% endif %}
            </del>
          </div> <!-- price-wrap.// -->
        </figcaption>
      </figure> <!-- card // -->
    </div> <!-- col // -->
    {% endfor %}
  </div>

</div>
</section>
{% endblock %}