up2u_mall/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('', views.cart_detail, name='cart_detail'),
]

up2u_mall/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('', views.orders, name='orders'),
]

up2u_mall/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
    path('all/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    # 1/coffee/
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('', views.home, name='home'),

]

up2u_mall/up2u_mall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)

up2u_mall/cart/models.py
from django.db import models

# Create your models here.

up2u_mall/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    """
    使用TypedChoiceField进行数量选择，并通过 coerce=int进行整数转换.
    """
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int,
                                label='数量')
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

up2u_mall/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product


# Create your views here.
@require_POST
def cart_add(request, product_id):
    # 构造购物车对象
    cart = Cart(request)
    # 把商品放到购物车
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                    quantity=cd['quantity'],
                    update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
            'update':True})

    # 返回页面
    context = {'cart': cart}
    return render(request, 'cart/detail.html', context)

up2u_mall/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  购物车
{% endblock %}

{% block mystyle %}
<link rel="stylesheet" href="{% static "css/cart.css" %}">
{% endblock %}

{% block content %}
<div class="container">
    <main class="card p-5">
      <h3>购物车</h3>
      <table class="cart">
        <thead>
          <tr>
            <th>图片</th>
            <th>商品</th>
            <th>数量</th>
            <th>删除</th>
            <th>单价</th>
            <th>总额</th>
          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
            {% with product=item.product %}
              <tr>
                <td>
                  <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                  </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                  <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="更新">
                    {% csrf_token %}
                  </form>
                </td>
                <td><a href="{% url "cart:cart_remove" product.id %}">删除</a></td>
                <td class="num">￥{{ item.price }}</td>
                <td class="num">￥{{ item.total_price }}</td>
              </tr>
            {% endwith %}
          {% endfor %}
          <tr class="total">
            <td>商品总额</td>
            <td colspan="4"></td>
            <td class="num text-right">￥{{ cart.get_total_price }}</td>
          </tr>
        </tbody>
      </table>
      <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">继续购物</a>
        <a href="{% url "orders:order_create" %}" class="button">
            去结算
          </a>
      </p>

        <hr>

     
    </main>
</div>
{% endblock %}